In [1]:
import numpy as np 

np.squeeze([[[[1],[2]],[3,4]]])

array([[list([1]), list([2])],
       [3, 4]], dtype=object)

In [2]:
np.array([[[[1,3],[2,3]],[3,4]]])

array([[[list([1, 3]), list([2, 3])],
        [3, 4]]], dtype=object)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.eye(3)[:,1]

array([0., 1., 0.])

In [19]:
for counter, value in enumerate([6,5,7]):
    print(counter, value)

0 6
1 5
2 7


In [20]:
enumerate([6,5,7])

In [22]:
for x in enumerate([6,5,7]):
    print (x)

(0, 6)
(1, 5)
(2, 7)
